#server:
#  port: 8092

spring:
  application:
    name: msvc-event
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/eventbd_microserv 
#    username: postgre
#    password: mateamargo
#  jpa:
#    hibernate: 
#      ddl-auto: create
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka